### ISSUE TITLE
Themenfindung

### ISSUE THREAD

**Issue by eirikjapp** [eirikjapp/web2_0#2]

**Comment by EmbeddedChristian** [comment]
Meine 1. Idee: Themenfindung ist schwer. Man könnte einen Dienst anbieten, der es erlaubt, dass Nutzer ihre Ideen für Webdienste posten können. Andere Nutzer könnten diese dann bewerten und kommentieren. Webentwickler hätten dann die Möglichkeit auf für sie von uns bereitgestellter Hard- und Software das Projekt zu realisieren. Das ganze wäre kostenlos, aber der Gewinn des Webdienstes ginge zu 5-10% an uns.

**Comment by EmbeddedChristian** [comment]
Idee 2: Dog sharing. Hundebesitzer können in ihrer Nähe andere Hundebesitzer finden, die bereit sind (für Geld oder kostenlos) sich für eine bestimmte Zeit um dessen Hunde zu kümmern. Wir könnten Geld aus den Transaktionen oder Werbung schlagen

**Comment by delpiero224** [comment]
Ergänzend noch die Idee von Timon kurz zusammengefasst

Erfassung der Menge an Kunden im Supermarkt o.ä., z.B. zur Auslastungssteuerung ... (Erkennung per Bluetooth?)
