### ISSUE TITLE
Auslastungssteuerung in Supermärkten etc.

### ISSUE THREAD

**Issue by TimonFelske** [eirikjapp/web2_0#3]
Die Idee ist, ein ähnliches System zu entwickeln, das Cap bereits für die Mensa vorgestellt hat. Bei Supermärkten ist häufig das Problem, dass es Zeiträume gibt, in denen alles überfüllt ist und in denen quasi nichts los ist. Der Ansatz wäre jetzt, anhand von Bluetooth Signalen festzustellen, wie viel im Supermarkt los ist und das auf einer Website oder ähnlichem anzuzeigen.

So könnte man beispielsweise in der Nähe der Kassen oder in der Umgebung, in der die Warteschlangen sind, Bluetooth Empfänger aufstellen. Wenn ein Gerät Bluetooth aktiviert hat, empfangen die Empfänger diese Signale und erhalten die Mac Adresse des Gerätes. Wenn nun im Bereich der Kassen sehr viele Mac-Adressen auftauchen, weiß man, dass sehr viele Leute anstehen. Je weniger Mac-Adressen auftauchen, desto weniger Leute stehen an. Da die Mac-Adresse eindeutig ist, kann man damit auf die Anzahl der Leute schließen (Wenn jeder nur ein Gerät dabei hat). 
Wenn man dann noch zusätzlich die Informationen bekommt, wie viele Kassen im Moment geöffnet sind, kann man anhand der Anzahl der Mac-Adressen auch Vorschläge machen, ob Kassen geöffnet oder geschlossen werden sollten.
Des weiteren wird auf einer Website angezeigt, ob es grade eine gute Zeit ist, einkaufen zu gehen oder ob es sehr voll ist.

Das System könnte man an Supermärkte verkaufen oder in Mensen etc. verwenden. Quasi überall, wo es Warteschlangen gibt.

**Comment by delpiero224** [comment]
Finde ich prinzipiell gut die Idee.

Die Frage ist halt: Was bietet es aus Kundensicht mehr als die Auslastungsanzeige, die Google Maps jetzt schon hat? Man hat ja die Infos lieber an einer Stelle, als jetzt ständig die Supermarktwebsite aufrufen zu müssen.

Den Vorteil hier sehe ich eher in der Sicht des Supermarktes, also z. B. dem Hinweis ans übrige Personal, doch bitte zusätzliche Kassen aufzumachen.

Frage ist: Wie genau ist so ne Bluetooth-Erkennung? Teilweise gibt es ja auch so große Kassenbereiche wie bei Real oder Kaufland, die man als Einkäufer gar nicht überblickt. Dann könnte man dem Kunden (per Bildschirm, Nachricht aufs Handy oder whatever) mitteilen, dass die Warteschlangen dort kürzer sind (wie z.B. am Airport)

**Comment by TimonFelske** [comment]
Bluetooth ist schon sehr genau. Also wenn man die Empfänger an Pfeiler oder an die Decke macht, dann empfangen die quasi alles von Handys. Alternativ könnte man auf Wifi verwenden

**Comment by EmbeddedChristian** [comment]
Prinzipiell eine gute Idee. Aber ich glaube auch, dass man das eher vor Ort als online nutzen würde. Ich würde wenn bei Bluetooth bleiben und nicht zu Wifi wechseln. Low energy bluetooth (als Beispiel), lässt sich einfacher länger autark betreiben

**Comment by delpiero224** [comment]
@TimonFelske Ich meinte auch eher, auf wie viel Meter man den Standort mit Bluetooth ca. eingrenzen kann. Denke mal, so 5 Meter sollten drin sein?

Davon würde ja abhängen, ob man den Kassenbereich (z. B. durch mehrere Beacons mit vergleichsweise geringer Reichweite)  genauer eingrenzen kann.

**Comment by TimonFelske** [comment]
Mit Bluetooth kann man die Position mit einfachen Berechnungen auf 2-3 Meter genau bestimmen.

**Comment by delpiero224** [comment]
2-3 Meter klingt ja gut brauchbar für den Zweck
